version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: auth_monitor_postgres
    environment:
      POSTGRES_DB: auth_monitor_db
      POSTGRES_USER: vussl
      POSTGRES_PASSWORD: auth_monitor_2306
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: